---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: n8n-secrets
  namespace: n8n
  labels:
    app: n8n
    component: secrets
stringData:
 DB_POSTGRESDB_PASSWORD: "changePassword"
 WORKFLOWS_DEFAULT_NAME: "New WF"
 N8N_SECURE_COOKIE: true
